#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=1:30:00
#PBS -N app-generate-parc-thal-amyg-hipp
#PBS -l vmem=20gb
#PBS -V

[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt

time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/connectome_workbench:1.5.0 ./run.sh

time singularity exec -e docker://brainlife/dipy:1.4.1 ./update_parc_label.py
